### ISSUE TITLE
Implement Profile Page

### ISSUE THREAD

**Issue by joaopsoliveira03** [nei-estg/nei-website#101]
See Fields and Update. Button for changing password.

**Comment by joaopsoliveira2003** [comment]
Profile update at the backend level is not implemented yet

**Comment by joaopsoliveira2003** [comment]
now that we have the profile picture in the navbar, when the users changes the profile picture it should update the localstorage ou find a better way to do it

**Comment by heyliceeee** [comment]
### TO DO LIST
 - [ ] save changes to the backend
