### ISSUE TITLE
Screen for different errors

### ISSUE THREAD

**Issue by joaopsoliveira2003** [nei-estg/nei-website#22]
e.g. token expired

**Comment by cynlik** [comment]
Isto é suposto ser um redirect para uma página de erro quando algo acontece? 

Exemplo:

User escreve uma rota que nao existe no ficheiro das rotas.
- Aparece uma pagina a dizer 404 not found?

**Comment by joaopsoliveira2003** [comment]
Sim é mais ou menos isso. Temos esse tipo de erro mas também podem surgir em outros casos como aceder a algo com o token expirado.

Estrutura do erro:
- HTTP Code
- Json: `{"detail": "blah blah blah"}`

Resumidamente: Tratar a tentativa de aceder a uma página que não exista no react e todo o tipo de erros que pode surgir com o axios desde o django estar down e retornar um http code diferente do suposto
