### ISSUE TITLE
Add Reset Password in Django

### ISSUE THREAD

**Issue by joaopsoliveira2003** [nei-estg/nei-website#46]

**Comment by joaopsoliveira2003** [comment]
hey @VidyaYadavv1519 ofc :))

**Comment by VidyaYadavv1519** [comment]
can you please elaborate more what exactly you want in this

**Comment by joaopsoliveira2003** [comment]
I was thinking about two endpoints: one where you specify your username and django sends an email to the user email and then other where you specify your old password and new password. 

I haven't thought much about the way to validate the code if it should be saved in the database. one possibility would be when the user creates an account, a code to change the password is given and then the user has to use that code if they want to reset the password. what do you think?

**Comment by VidyaYadavv1519** [comment]
According to me i think the first one, one where you specify your username and django sends an email to the user email and then.   Also have you already made login and register page then accordingly i can implement the Reset Password functionality.

**Comment by joaopsoliveira2003** [comment]
the login is working, register is not complete yet but will be

**Comment by VidyaYadavv1519** [comment]
okay, so i will implement the reset password functionality.

**Comment by VidyaYadavv1519** [comment]
hey, i am getting this issue on running server.                                                                                                                                                  raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.                                                                       A server error occurred.  Please contact the administrator.                                                                                                                            

can you please help me with this ?

**Comment by joaopsoliveira2003** [comment]
are running through docker-compose? did you set up the .env file based on the . env.example? Read README and if you still need help tell me

**Comment by VidyaYadavv1519** [comment]
Tried its not working, i don't know about docker done everything to set up but my docker engine is not working .

**Comment by joaopsoliveira2003** [comment]
contact me on discord: joaopsoliveira

**Comment by joaopsoliveira2003** [comment]
@VidyaYadavv1519 did you got it working?
