### ISSUE TITLE
Implement Password Reset Mechanism

### ISSUE THREAD

**Issue by joaopsoliveira03** [nei-estg/nei-website#97]
Generate a random code and send via email and save somewhere but not on DB.

**Comment by joaopsoliveira2003** [comment]
Implemented in backend, frontend missing

**Comment by heyliceeee** [comment]
- [ ] The user enters their username, if they match they will receive an email with the code, otherwise they will not receive the email.
- [ ] After the user receives the email with the code, on the same page (updates the state) they will enter the code received and the new password.
